# Custom Language File for Launcher Customizer

[ejs.app]
title = "Chillax Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Khreight/ChillaxLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/Khreight/ChillaxLauncher"
supportLink = "https://github.com/Khreight/ChillaxLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur le serveur Chillax"
welcomeDescription = "Je vais pas passer par 4 chemins, amusez-vous bien ZEBIIII"
